/*
 * This source file was generated by the Gradle 'init' task
 */
package com.mkdirjava.schema;
import org.apache.kafka.connect.data.Schema;
import org.apache.kafka.connect.data.SchemaBuilder;

public class ValueSchema {
    
    public static Schema getSchema(){
        return SchemaBuilder.struct()
                .field("id", Schema.INT64_SCHEMA)
                .field("name", Schema.STRING_SCHEMA)
                .build();
    }
}
